language: node_js
node_js:
  - "node"
  - "lts/*"
  - "4"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@">=5.6.0"
script:
  - npm run lint
  - npm run coverage
  - npm run compile
after_success:
  - ./node_modules/.bin/codecov -f coverage/coverage-final.json