language: node_js
node_js:
  - node
  - lts/*
  - lts/argon
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      before_install:
        - npm i -g npm@">=5.6.0"
      script:
        - npm run lint
        - npm run coverage
      after_success:
        - ./node_modules/.bin/codecov -f coverage/coverage-final.json
    - stage: dummy stage
      node_js: "lts/*"
      script: echo "Hello from dummy stage!"
