language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
- lts/*
- lts/argon
before_install:
- npm i -g npm@">=5.6.0"
script:
- npm run lint
- npm run coverage
after_success:
- "./node_modules/.bin/codecov -f coverage/coverage-final.json"
stages:
- test
- name: release
  if: tag IS present
jobs:
  include:
  - stage: release
    node_js: lts/*
    before_install: true
    script:
    - npm version --no-git-tag-version --allow-same-version $TRAVIS_TAG
    - npm run compile && npm pack
    after_success: true
    deploy:
    - provider: releases
      api_key:
        secure: NVlZS2iTQlylmC+vFGAOAN87gCiIHcr8i1WUVd7e1l4QLpkCbYBI+poZhdsJBI7Q69dEftOVgUFNal+jHvKwlY97ibHjZzeQ0OZ66IfEa1CqF3I6r2V2JL3+PCdNCvZTsYy5w2B0malgO+MeZ8eU3/bmKT9fQQ/T7wTzJzmVLl+csmC5GG9f8QLeIkRBQ1DsS0XN31AA/4z8U4uyBJGGWy2YiF5cplBPrUZfmGRaXdN5vMJOtTPVc80gjw5akXJMer/dYCB1oUCcSz/E5y38Frugpb0V7tVln8CkYaB92lwVECfby09BltKDW6iOmCA2vuMmXDkqZDAnqmzI9egQWRXhGaINRfrGDurDaSj4n0RcMIcF4i3Mh1JSpHfsiEzVOXQ4rOtZllPOqyxj0aF116L3PxOQTzpSpZ6olvQTeGYwYtj9LScpdA+wx/XG9FP3HGqwfJc1rAg1SPYdc1JiYal77nRDBs9z6djeNPFP5iAHXSdc7vMygP4F+2Aq7qwuWswH++9jx4jaHpB/lcoLVnk0xNejmjwvLKxMwdgGxXbicyUsTblpfcXvjtOA5MALAq+FFwMWqHoJZ90/qlgAvDdU/D/AdIj1LETPosEhEsRpmXrhMcaRYrOE3rduY7fTJl+Fy20y8ETop2n0xxRJqE6ey3Mqcivj9GdDCcZ8FUg=
      file: atlas-doc-*.tgz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
    - provider: npm
      email: gesau@hotmail.co.uk
      api_key:
        secure: aMg5YUEAoztaF3QT8WFmk4cfO/enPV77fXEkf1uSX0bM7hHqtiK0mT5gkj97OxHyfss9Nz1FCM7KwAJdaEEEhnY3SbaXTpbEswKP9gBWwSMYM7NMKuzHdhzcD8sUOV0/7DY0Nt12uQMpXo8MM5EADmjdAn5fMru6HKytY/1iOiNFdesYaRBERCk9IK3kpJa5DUro9foyKMDWOV+wblDJ4n7yTA5kqN0yyVIk5bW/qIl6EvuQgWYow2SF0IscObndzK3S8a9THUmi/42XpVZnWaI+EA7n4L8lSXZ2VV4RhOUGH9MTmrO9FW0UNn/hswozuTlgkJcALhWuYvsumm4My5GaCurO118VyXg6Xc8mF+hVmwK9NeMqcCWNKHDPqkDYzgkEpeS2w94IviDoP5di6dS35LHIq2R2h/MBSwwNispeQbl243gqZHxt7Znut/ohmiS8IfcaGyLbPNVyrvxrqQBkpHnZtmujQK/ZomP/BbU84GKCNxnSICl5/R8z47Ch6vnbQ6nwiQi2pJF+N8Y1NiQO6djD5dOmiHhj8fLd3rl/60FX+LA/83HJKGhKpnPw5lTOXT9vNypYpIwybZ/xlmW6R181dKYng445UtzQxpCSQBjDofN9rjgJvLIOcADMkaPwLOyoFHkm6RXz6JjwyGa4q+mdAgeqIJZnblEMbxE=
      skip_cleanup: true
      on:
        tags: true
